[package]
name = "conrod-cli"
description = "Conrod from the command line."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "conrod-cli"
path = "src/main.rs"

[dependencies]
conrod-core = { path = "../conrod-core" }
conrod-engine = { path = "../conrod-engine" }
serde_json = "1"
